version: '2.1'
services:
 openldap:
    image: bilaldemirci/openldap
    ports:
     - 389:389
 management-center:
    image: hazelcast/management-center:3.12
    volumes: 
     - ../management-center-ldap/security.properties:/data/security.properties
     - ../management-center-ldap/ldap.properties:/data/ldap.properties
    depends_on:
     - openldap 
    ports:
     - 8080:8080
    links:
     - "openldap:ldapIP"
